title: Mariann Proos # your name (or website title) here
logo: "/images/profilepic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Hi! I am Mariann Proos, a junior research fellow at the University of Tartu.
  I am interested in how language works, how it's connected to our minds and our surroundings. I work in semantics focusing on polysemy and meaning variation across languages. I have experience with both experimental and corpus-based methods of language research and I strongly believe in methodological pluralism.
  <br><br>
  <a href="https://www.researchgate.net/profile/Mariann_Proos">View my ResearchGate profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

<meta name="google-site-verification" content="_4rdjW8chfgTFVVAQwum-KDMUsislYZuixTpvwtZy44" />
